In [22]:
import numpy as np
datas=[]
f=open('student.txt','r')
while True:
    s=f.readline() #s:'1,aaa,67,87,56\n'
    
    if s=='':
        break
        
    s=s.split('\n')[0] #s: '1,aaa,67,87,56'
    stu=s.split(',')  #stu: ['1','aaa','67','87','56']
    
    for i in range(0,2):
        stu.append(0) #['1','aaa','67','87','56',0,0]
    datas.append(stu)
f.close()

datas
arr=np.array(datas) #datas 리스트를 numpy 배열로 변환
names=arr[:,0] #모든 줄 0번칼럼(이름)만 추출하여 names에 저장
x=arr[:,1:] #모든 열 1~끝컬럼 (번호,국,영,수) 추출해서 x에 저장
score=x.astype(np.float32) #점수 배열 요소 타입을 float으로 변경
# for i in score: #모든 줄의 총점 및 평균 계산.
#     k=i[1:4]
#     sum1=k.sum()
#     i[4]=sum1
#     i[5]=sum1/3
    
score[:,4]=score[:,1:4].sum(axis=1)
score[:,5]=score[:,4]/3
score


array([[  1.      ,  43.      ,  65.      ,  78.      , 186.      ,
         62.      ],
       [  2.      ,  76.      ,  98.      ,  54.      , 228.      ,
         76.      ],
       [  3.      ,  98.      ,  67.      ,  54.      , 219.      ,
         73.      ],
       [  4.      ,  54.      ,  98.      ,  67.      , 219.      ,
         73.      ],
       [  5.      ,  98.      ,  65.      ,  34.      , 197.      ,
         65.666664]], dtype=float32)

In [23]:
#학생들의 국어총점, 영어총점, 수학총점

sums=score.sum(axis=0)
print('국어총점:', sums[1])
print('영어총점:', sums[2])
print('수학총점:', sums[3])
print('전체총점:', sums[4])
print('전체평균:', sums[5])


국어총점: 369.0
영어총점: 393.0
수학총점: 287.0
전체총점: 1049.0
전체평균: 349.66666


In [24]:
# #총점 정렬
# for i in range(0,4):
#     for j in range(0,4-i):
#         if score[i][4]> score[]

SyntaxError: invalid syntax (<ipython-input-24-d305c35d3708>, line 4)

In [27]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [29]:
a>1

array([False, False,  True,  True,  True])

In [32]:
a<4

array([ True,  True,  True,  True, False])

In [34]:
np.logical_and(a>1,a<4)

array([False, False,  True,  True, False])

In [36]:
np.logical_or(a<1,a>3)

array([ True, False, False, False,  True])

In [2]:
import pandas as pd

In [6]:
s2=pd.Series({'kor':65, 'eng':78, 'math':89})
s2['kor']
s2['math']

89

In [14]:
import numpy as np
idx=[] #사용할 index
vals=[] #시리즈로 생성할 값

names=['aaa','bbb','ccc','ddd','eee']

for i in range(1,6): #인덱스와 성적 자동 생성
    s='student'+str(i)
    idx.append(s) #생성한 인덱스를 idx에 저장
    
    val=np.random.randint(0,100,(3))
    vals.append(val)
    
stu=pd.Series(vals,index=idx)
stu

student1    [65, 51, 14]
student2    [76, 52, 46]
student3     [84, 69, 8]
student4    [24, 47, 94]
student5    [83, 16, 96]
dtype: object

In [12]:
idx

['student1', 'student2', 'student3', 'student4', 'student5']

In [15]:
vals

[array([65, 51, 14]),
 array([76, 52, 46]),
 array([84, 69,  8]),
 array([24, 47, 94]),
 array([83, 16, 96])]

In [23]:
data=[[1,2,3],[4,5,6],[7,8,9]]
d1=pd.DataFrame(data)
d1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [27]:
my_index=['row1','row2','row3']
my_col=['col1','col2','col3']
d2=pd.DataFrame(data,index=my_index,columns=my_col)
d2

col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9

In [31]:
index=['stu1','stu2','stu3','stu4']
cols=['name','num','kor','eng','math']
vals=[['aaa',1,54,74,64],
     ['bbb',2,56,96,69],
     ['ccc',3,97,98,91],
     ['ddd',4,95,87,64]]
d3=pd.DataFrame(vals,index=index,columns=cols)
d3

name  num  kor  eng  math
stu1  aaa    1   54   74    64
stu2  bbb    2   56   96    69
stu3  ccc    3   97   98    91
stu4  ddd    4   95   87    64

In [33]:
d3.index

Index(['stu1', 'stu2', 'stu3', 'stu4'], dtype='object')

In [35]:
d3.columns

Index(['name', 'num', 'kor', 'eng', 'math'], dtype='object')

In [37]:
d3.values

array([['aaa', 1, 54, 74, 64],
       ['bbb', 2, 56, 96, 69],
       ['ccc', 3, 97, 98, 91],
       ['ddd', 4, 95, 87, 64]], dtype=object)

In [43]:
dic={
    'name':['aaa','bbb','ccc','ddd'],
    'num' :[1,2,3,4],
    'kor' :[54,56,97,95],
    'eng' :[74,96,98,87],
    'math':[64,69,91,64],
    'index':['sut1','stu2','stu3','stu4']
}
d4=pd.DataFrame(dic,index=index)
d4

idx=np.arange(1,5)
d4=pd.DataFrame(dic,index=idx)
d4

name  num  kor  eng  math index
1  aaa    1   54   74    64  sut1
2  bbb    2   56   96    69  stu2
3  ccc    3   97   98    91  stu3
4  ddd    4   95   87    64  stu4

In [45]:
a=pd.Series([1,2,3,4])
b=pd.Series([5,4,5])
a+b

0    6.0
1    6.0
2    8.0
3    NaN
dtype: float64

In [48]:
data=pd.read_csv('a.csv')
data

이름  국어  영어  수학
0  aaa  43  54  65
1  bbb   7  67  87
2  ccc  54  65  76

In [54]:
acc=pd.read_csv('car_accident.csv',encoding='euc-kr')
acc


발생년    사고건수  사망자수   중상자수    경상자수  부상신고자수
0  2015  232035  4621  92522  233646   24232
1  2016  220917  4292  82463  226283   22974
2  2017  216335  4185  78212  223200   21417
3  2018  217148  3781  74258  227511   21268
4  2019  229600  3349  72306  245524   23882

In [55]:
acc.describe()

발생년           사고건수         사망자수          중상자수           경상자수  \
count     5.000000       5.000000     5.000000      5.000000       5.000000   
mean   2017.000000  223207.000000  4045.600000  79952.200000  231232.800000   
std       1.581139    7210.825161   491.552439   8034.621534    8845.056851   
min    2015.000000  216335.000000  3349.000000  72306.000000  223200.000000   
25%    2016.000000  217148.000000  3781.000000  74258.000000  226283.000000   
50%    2017.000000  220917.000000  4185.000000  78212.000000  227511.000000   
75%    2018.000000  229600.000000  4292.000000  82463.000000  233646.000000   
max    2019.000000  232035.000000  4621.000000  92522.000000  245524.000000   

             부상신고자수  
count      5.000000  
mean   22754.600000  
std     1369.400526  
min    21268.000000  
25%    21417.000000  
50%    22974.000000  
75%    23882.000000  
max    24232.000000